In [1]:
import pandas as pd

In [11]:
region = "union_bay"

In [12]:
df = pd.read_csv("data/" + region + "_barchart.tsv", sep="\t", header=None, index_col=0)
df = df.drop(columns=[49])
df.index.name = None
df

,1,2,3,4,5,6,7,8,9,10,...,39,40,41,42,43,44,45,46,47,48
Emperor Goose,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Snow Goose,0.008392,0.027523,0.007005,0.000000,0.003854,0.010163,0.003711,0.001500,0.004862,0.001961,...,0.052314,0.075067,0.015504,0.035316,0.013232,0.020896,0.015873,0.000000,0.009036,0.017065
Ross's Goose,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Snow/Ross's Goose,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.001340,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Graylag Goose,0.000000,0.000000,0.000000,0.000000,0.001927,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Rose-breasted/Black-headed Grosbeak,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Lazuli Bunting,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Indigo Bunting,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
passerine sp.,0.006993,0.005505,0.007005,0.002805,0.001927,0.010163,0.012987,0.009728,0.006483,0.007843,...,0.032193,0.018767,0.021318,0.011152,0.022684,0.011940,0.010582,0.005602,0.009036,0.017065
bird sp.,0.006993,0.003670,0.005254,0.001403,0.009634,0.008130,0.003711,0.005837,0.006483,0.007843,...,0.000000,0.009383,0.007752,0.009294,0.020794,0.007463,0.007937,0.005602,0.003012,0.005119

In [13]:
# Filter out hybrids and generics
df = df[
    [
        ("sp." not in bird) and (" x " not in bird) and ("/" not in bird)
        for bird in df.index
    ]
].copy()
df

,1,2,3,4,5,6,7,8,9,10,...,39,40,41,42,43,44,45,46,47,48
Emperor Goose,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Snow Goose,0.008392,0.027523,0.007005,0.000000,0.003854,0.010163,0.003711,0.001500,0.004862,0.001961,...,0.052314,0.075067,0.015504,0.035316,0.013232,0.020896,0.015873,0.000000,0.009036,0.017065
Ross's Goose,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Graylag Goose,0.000000,0.000000,0.000000,0.000000,0.001927,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Greater White-fronted Goose,0.026573,0.069725,0.026270,0.053296,0.059730,0.058943,0.068646,0.070039,0.066451,0.050980,...,0.094567,0.044236,0.034884,0.059480,0.117202,0.119403,0.050265,0.039216,0.054217,0.025597
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wilson's Warbler,0.002797,0.001835,0.000000,0.001403,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.002012,0.001340,0.001938,0.007435,0.011342,0.005970,0.013227,0.002801,0.000000,0.001500
Western Tanager,0.004196,0.000000,0.000000,0.000000,0.000000,0.000000,0.001855,0.000000,0.000000,0.000000,...,0.000000,0.008043,0.021318,0.020446,0.007561,0.002985,0.000000,0.002801,0.000000,0.000000
Black-headed Grosbeak,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.001859,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Lazuli Bunting,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Indigo Bunting,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [14]:
df.to_csv("data/" + region + "_barchart.csv")