In [1]:
import geopandas as gpd

In [2]:
gdf = gpd.read_file("../raw/gz_2010_us_050_00_20m.json", encoding='cp1252')
gdf

,GEO_ID,STATE,COUNTY,NAME,LSAD,CENSUSAREA,geometry
0,0500000US01001,01,001,Autauga,County,594.436,"POLYGON ((-86.49677 32.34444, -86.7179 32.4028..."
1,0500000US01009,01,009,Blount,County,644.776,"POLYGON ((-86.5778 33.76532, -86.75914 33.8406..."
2,0500000US01017,01,017,Chambers,County,596.531,"POLYGON ((-85.18413 32.87052, -85.12342 32.772..."
3,0500000US01021,01,021,Chilton,County,692.854,"POLYGON ((-86.51734 33.02057, -86.51596 32.929..."
4,0500000US01033,01,033,Colbert,County,592.619,"POLYGON ((-88.13999 34.5817, -88.13925 34.5878..."
...,...,...,...,...,...,...,...
3216,0500000US51001,51,001,Accomack,County,449.496,"MULTIPOLYGON (((-75.24227 38.02721, -75.29687 ..."
3217,0500000US51021,51,021,Bland,County,357.725,"POLYGON ((-81.2251 37.23487, -81.20477 37.2430..."
3218,0500000US51027,51,027,Buchanan,County,502.763,"POLYGON ((-81.9683 37.5378, -81.92787 37.51212..."
3219,0500000US51037,51,037,Charlotte,County,475.271,"POLYGON ((-78.44332 37.0794, -78.49303 36.8912..."
3220,0500000US51041,51,041,Chesterfield,County,423.297,"POLYGON ((-77.8518 37.35487, -77.85515 37.4183..."

In [3]:
mapping = {
    "01": "AL",
    "02": "AK",
    "04": "AZ",
    "05": "AR",
    "06": "CA",
    "08": "CO",
    "09": "CT",
    "10": "DE",
    "11": "DC",
    "12": "FL",
    "13": "GA",
    "15": "HI",
    "16": "ID",
    "17": "IL",
    "18": "IN",
    "19": "IA",
    "20": "KS",
    "21": "KY",
    "22": "LA",
    "23": "ME",
    "24": "MD",
    "25": "MA",
    "26": "MI",
    "27": "MN",
    "28": "MS",
    "29": "MO",
    "30": "MT",
    "31": "NE",
    "32": "NV",
    "33": "NH",
    "34": "NJ",
    "35": "NM",
    "36": "NY",
    "37": "NC",
    "38": "ND",
    "39": "OH",
    "40": "OK",
    "41": "OR",
    "42": "PA",
    "44": "RI",
    "45": "SC",
    "46": "SD",
    "47": "TN",
    "48": "TX",
    "49": "UT",
    "50": "VT",
    "51": "VA",
    "53": "WA",
    "54": "WV",
    "55": "WI",
    "56": "WY",
}

In [4]:
gdf["state"] = gdf["STATE"].map(mapping)
gdf

,GEO_ID,STATE,COUNTY,NAME,LSAD,CENSUSAREA,geometry,state
0,0500000US01001,01,001,Autauga,County,594.436,"POLYGON ((-86.49677 32.34444, -86.7179 32.4028...",AL
1,0500000US01009,01,009,Blount,County,644.776,"POLYGON ((-86.5778 33.76532, -86.75914 33.8406...",AL
2,0500000US01017,01,017,Chambers,County,596.531,"POLYGON ((-85.18413 32.87052, -85.12342 32.772...",AL
3,0500000US01021,01,021,Chilton,County,692.854,"POLYGON ((-86.51734 33.02057, -86.51596 32.929...",AL
4,0500000US01033,01,033,Colbert,County,592.619,"POLYGON ((-88.13999 34.5817, -88.13925 34.5878...",AL
...,...,...,...,...,...,...,...,...
3216,0500000US51001,51,001,Accomack,County,449.496,"MULTIPOLYGON (((-75.24227 38.02721, -75.29687 ...",VA
3217,0500000US51021,51,021,Bland,County,357.725,"POLYGON ((-81.2251 37.23487, -81.20477 37.2430...",VA
3218,0500000US51027,51,027,Buchanan,County,502.763,"POLYGON ((-81.9683 37.5378, -81.92787 37.51212...",VA
3219,0500000US51037,51,037,Charlotte,County,475.271,"POLYGON ((-78.44332 37.0794, -78.49303 36.8912...",VA
3220,0500000US51041,51,041,Chesterfield,County,423.297,"POLYGON ((-77.8518 37.35487, -77.85515 37.4183...",VA

In [5]:
gdf["county"] = gdf["NAME"]
gdf

,GEO_ID,STATE,COUNTY,NAME,LSAD,CENSUSAREA,geometry,state,county
0,0500000US01001,01,001,Autauga,County,594.436,"POLYGON ((-86.49677 32.34444, -86.7179 32.4028...",AL,Autauga
1,0500000US01009,01,009,Blount,County,644.776,"POLYGON ((-86.5778 33.76532, -86.75914 33.8406...",AL,Blount
2,0500000US01017,01,017,Chambers,County,596.531,"POLYGON ((-85.18413 32.87052, -85.12342 32.772...",AL,Chambers
3,0500000US01021,01,021,Chilton,County,692.854,"POLYGON ((-86.51734 33.02057, -86.51596 32.929...",AL,Chilton
4,0500000US01033,01,033,Colbert,County,592.619,"POLYGON ((-88.13999 34.5817, -88.13925 34.5878...",AL,Colbert
...,...,...,...,...,...,...,...,...,...
3216,0500000US51001,51,001,Accomack,County,449.496,"MULTIPOLYGON (((-75.24227 38.02721, -75.29687 ...",VA,Accomack
3217,0500000US51021,51,021,Bland,County,357.725,"POLYGON ((-81.2251 37.23487, -81.20477 37.2430...",VA,Bland
3218,0500000US51027,51,027,Buchanan,County,502.763,"POLYGON ((-81.9683 37.5378, -81.92787 37.51212...",VA,Buchanan
3219,0500000US51037,51,037,Charlotte,County,475.271,"POLYGON ((-78.44332 37.0794, -78.49303 36.8912...",VA,Charlotte
3220,0500000US51041,51,041,Chesterfield,County,423.297,"POLYGON ((-77.8518 37.35487, -77.85515 37.4183...",VA,Chesterfield

In [6]:
gdf = gdf[["state", "county", "geometry"]]
gdf

     state        county                                           geometry
0       AL       Autauga  POLYGON ((-86.49677 32.34444, -86.7179 32.4028...
1       AL        Blount  POLYGON ((-86.5778 33.76532, -86.75914 33.8406...
2       AL      Chambers  POLYGON ((-85.18413 32.87052, -85.12342 32.772...
3       AL       Chilton  POLYGON ((-86.51734 33.02057, -86.51596 32.929...
4       AL       Colbert  POLYGON ((-88.13999 34.5817, -88.13925 34.5878...
...    ...           ...                                                ...
3216    VA      Accomack  MULTIPOLYGON (((-75.24227 38.02721, -75.29687 ...
3217    VA         Bland  POLYGON ((-81.2251 37.23487, -81.20477 37.2430...
3218    VA      Buchanan  POLYGON ((-81.9683 37.5378, -81.92787 37.51212...
3219    VA     Charlotte  POLYGON ((-78.44332 37.0794, -78.49303 36.8912...
3220    VA  Chesterfield  POLYGON ((-77.8518 37.35487, -77.85515 37.4183...

[3221 rows x 3 columns]

In [ ]:
gdf.to_file("../web/data/US.geojson", driver="GeoJSON")